import { Testimonial } from "../model";

const avatarUrl = (name: string) =>
  `/avatars/${name.toLowerCase().replace(" ", "-")}-avatar.png`;

export const testimonials: Testimonial[] = [
  {
    rating: 5,
    text: "Since implementing this CRM, our sales have increased by 30% in just three months. It's become an integral part of our growth strategy.",
    user: {
      avatar: avatarUrl("Marx Hershey"),
      name: "Marx Hershey",
      occupation: "Project Manager",
    },
  },
  {
    rating: 4.5,
    text: "This CRM has transformed how we interact with our customers. The marketing automation and customer insights have been game-changers for us. Highly recommended!",
    user: {
      avatar: avatarUrl("Tyra Dhillon"),
      name: "Tyra Dhillon",
      occupation: "Software Tester",
    },
  },
  {
    rating: 4.5,
    text: "I was looking for a CRM that was easy to use and could adapt to my business. This CRM has exceeded my expectations. It's simple, intuitive, and customizable.",
    user: {
      avatar: avatarUrl("Courtney Henry"),
      name: "Courtney Henry",
      occupation: "UI/UX Designer",
    },
  },
  {
    rating: 5,
    text: "The sales pipeline and automation tools have been a massive time-saver. We can now manage leads and deals more efficiently, which has had a direct impact on our bottom line.",
    user: {
      occupation: "Team Leader",
      name: "Marvin McKinney",
      avatar: avatarUrl("Marvin McKinney"),
    },
  },
  {
    rating: 5,
    text: "The reports generated by this CRM have allowed us to track and measure our performance better than ever. It's helped us identify areas for improvement and growth opportunities.",
    user: {
      occupation: "Software Developer",
      name: "Roselle Ehrman",
      avatar: avatarUrl("Roselle Ehrman"),
    },
  },
  {
    rating: 5,
    text: "The ability to segment customers and personalize our marketing campaigns has led to a significant increase in conversion rates. It's been a game-changer for our e-commerce business.",
    user: {
      occupation: "Software Development Manager",
      name: "Floyd Miles",
      avatar: avatarUrl("Floyd Miles"),
    },
  },
  {
    rating: 5,
    text: "Our customer support has become more organized and efficient with this CRM. The ticketing system and knowledge base features have made a significant difference in how we serve our customers.",
    user: {
      occupation: "Scrum Master",
      name: "Lauralee Quintero",
      avatar: avatarUrl("Lauralee Quintero"),
    },
  },
  {
    rating: 4.5,
    text: "The collaboration features in this CRM have greatly improved how our teams work together. Sharing information and coordinating has never been easier.",
    user: {
      occupation: "Ethical Hacker",
      name: "Kylee Danford",
      avatar: avatarUrl("Kylee Danford"),
    },
  },
  {
    rating: 5,
    text: "This CRM seamlessly integrated with our existing systems. The implementation was a breeze, and it's made a significant difference in our data management.",
    user: {
      occupation: "Scrum Master",
      name: "Dianne Russell",
      avatar: avatarUrl("Dianne Russell"),
    },
  },
];
