import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/widgets/header/header";
import Footer from "@/widgets/footer/footer";
import { TooltipProvider } from "@/shared/ui/tooltip/tooltip";
import clsx from "clsx";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "relative overflow-x-clip")}>
        <TooltipProvider>
          <Header />
          <div className="pt-22 h-screen flex flex-col justify-between items-center">
            {children}
            <Footer />
          </div>
        </TooltipProvider>
      </body>
    </html>
  );
}
